[theme]
base = "dark"
primaryColor = "#65e1c0"
backgroundColor = "#0b1119"
secondaryBackgroundColor = "#131e2b"
textColor = "#e6edf5"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
